<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DownloadPlayer</name>
   <tag></tag>
   <elementGuidId>9fa4b9b1-30d5-436a-8212-37dd328d354d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//admin-extensions/div[2]/div/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
