<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DownloadEditor</name>
   <tag></tag>
   <elementGuidId>6b83e756-d122-48a8-ac2b-ef86f8b2940b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//admin-extensions/div[2]/div/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
